baseURL = "https://engineering.amaysim.com.au/"
languageCode = "en-us"
title = "amaysim engineering"
menus = "test"
paginate = 10
theme = "amaysim-engineering-blog"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params]
    disqusShortname = "yunspace"
    googleAnalytics = "UA-123-45"