baseURL = "https://engineering.amaysim.com.au/"
languageCode = "en-us"
title = "amaysim engineering"
paginate = 10
theme = "hugo-theme-minos"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params]
    disqusShortname = "yunspace"